### ISSUE TITLE
Drawer does not hide when menu item's text or icon is clicked 

### ISSUE THREAD

**Issue by ethanhann** [beekmanlabs/tuxedo-menu#2]
This is a compatibility issue for menus generated by eeh-navigation where the menu item has multiple nested **span** elements under an **a** element.

**Comment by ethanhann** [comment]
Resolved by 1713c0d891aaae7bc0438c82ab82464276ba1477. Released version 0.5.2 with the fix.

**Comment by parakastha** [comment]
Bower install downloads latest version as 0.5.1. Please update it. Thanks Ethan.

**Comment by ethanhann** [comment]
There was a weird problem where bower was looking at the wrong repo. Nothing to worry about. You should see that tag now.

**Comment by parakastha** [comment]
Thanks a bunch again.. yes i am able to get the latest now. Just one last small issue :( on nested menus clicking on the parent menu (li) expands the child (as expected), however if you click on the menu text itself (span) it hides the menu instead of expanding the child.

**Comment by ethanhann** [comment]
There is currently no support for material icons because of the way the icon library's markup works. The libraries are only supported if they work like this:

``` html
<i class="BASE_CLASS ICON_CLASS"></i>
```

Material icons work like this:

``` html
<i class="BASE_CLASS">ICON_CLASS</i>
```

In the future please create a new issue if you have questions unrelated to this issue.

**Comment by parakastha** [comment]
ok. Thanks Ethan.
